### ISSUE TITLE
Format Error, not a PDF or Corrupted

### ISSUE THREAD

**Issue by Sanaullahbugti** [foxitsoftware/react-native-foxitpdf#15]
I am trying Example code and file structure still getting format errors. The file is ok and opening in other applications

**Comment by xinqiangSong** [comment]
Hello, can you help confirm the following questions
1: What platform are you using （Android /iOS）?
2: What version is the device ?
3: Do you have license (rdk_sn and rdk_key )?
4: You need to provide the code used to open the document

thanks

**Comment by Sanaullahbugti** [comment]
1-Android
2-  "@foxitsoftware/react-native-foxitpdf": "^8.3.0",
    "react": "18.0.0",
    "react-native": "0.69.4"
3- yes I have trial keys
4- i dont have any code to provide open docs 
  FoxitPDF.openDocument('https://pdftron.s3.amazonaws.com/downloads/pl/PDFTRON_mobile_about.pdf','',uiextensions_config);

**Comment by xinqiangSong** [comment]
Hi, currently our plugin only supports opening local files. If you need to support opening url,  we can provide you with a hotfix version, Do you need it?

**Comment by Sanaullahbugti** [comment]
I tried local as well. That also did not work. Can you please have look.

**Comment by xinqiangSong** [comment]
Do you have any errors? Can you provide your code

**Comment by xinqiangSong** [comment]
> Do you have any errors? Can you provide your code

It may be that your path is wrong or the path does not exist

**Comment by Sanaullahbugti** [comment]
Actually I follow example project and place file as same in sample project

**Comment by xinqiangSong** [comment]
> Actually I follow example project and place file as same in sample project
==============
Can you post your local file?

**Comment by Sanaullahbugti** [comment]
Here is the screenshot 
![image](https://user-images.githubusercontent.com/39256766/184052337-096ba608-1106-430c-954b-aac5179c2166.png)

**Comment by Sanaullahbugti** [comment]
> Do you have any errors? Can you provide your code
No, I did not get any error

**Comment by Sanaullahbugti** [comment]
> 



> Hi, currently our plugin only supports opening local files. If you need to support opening url, we can provide you with a hotfix version, Do you need it?

Yes, I actually need it. Our docs are in the s3 bucket so we use URLs

**Comment by xinqiangSong** [comment]
> Here is the creenshot ![image](https://user-images.githubusercontent.com/39256766/184052337-096ba608-1106-430c-954b-aac5179c2166.png)

Hello, the local path refers to the path on the device, not the path of the file on the PC side. You should copy the file to the virtual machine or the device and then open it. For example, if you copy the file to the root directory of the device, at this time the file The path should be /storage/emulated/0/xxx.pdf

**Comment by Sanaullahbugti** [comment]
@xinqiangSong @yongliang-huang @CancerQ 
I tried the local path as well but giving me the same error. Path I am getting after download is 
content://com.android.externalstorage.documents/tree/primaryDownload/Download/document/primaryDownload/Download/BEDFORD STORAGE DISPLAYS SAFETY AUDIT 24-04-22 (20).pdf
