### ISSUE TITLE
Android: Does not compile RN: 0.57.4

### ISSUE THREAD

**Issue by marksturm** [foxitsoftware/react-native-foxitpdf#5]
I start testing the whole thing tonight with a totaly fresh app and using the install-guide:

It ends with:
`Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.`

I fixed that by adding:

`    implementation 'com.android.support:design:27.1.0'`

in the build.gradle dependencies.

But im currently not able to open the sample.pdf so far. Its jus says "unable to open this file"

**Comment by xinqiangSong** [comment]
Please make sure that your file path is correct.

If you are using Android version: Add the file path location of the PDF inside your project.
For example, if the file is in your sdcard folder: FoxitPDF.openPDF('/sdcard/0/download/xxx.pdf')

**Comment by marksturm** [comment]
Yeah, i missed the part that genymotion used /sdcard/download/xxx.pdf instead of 0,1,2 and so on. Anyways its open the pdf file now.
