### ISSUE TITLE
Ios build fails

### ISSUE THREAD

**Issue by dmitri-wm** [foxitsoftware/react-native-foxitpdf#6]
Hello.
Having issue with installation:
Created fresh react-native app
Used this [guide](https://developers.foxitsoftware.com/kb/article/developer-guide-foxit-pdf-sdk-for-mobile-ios/)  to integrate foxit pdf with xcode 
Followed instructions from readme.
And on running command 
`react-native run-ios `
getting error 
```

▸ Compiling PDFManager.m

❌  /Users/dk/code/offline_viewer/node_modules/@foxitsoftware/react-native-foxitpdf/lib/ios/FoxitPDF/PDFManager.h:9:9: 'FoxitRDK/FSPDFViewControl.h' file not found

#import <FoxitRDK/FSPDFViewControl.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~


** BUILD FAILED **

```

With same error fails https://github.com/foxitsoftware/react-native-foxitpdf/tree/master/example 

Will appreciate any advice here.

**Comment by timkomip** [comment]
@dmitri-wm Did you fix this? I am having the same issue.

**Comment by niuemperor** [comment]
hi @timkomip 
may be you can follow the guide on github readme 
https://github.com/foxitsoftware/react-native-foxitpdf/blob/master/README.md

will resolved this problem.

**Comment by timkomip** [comment]
I did a dumb 😆 
It is very important that you follow directions and "copy libs folder into the component’s ios folder". I did not realize that the RN Foxit xcodeproj references the libs folder and it has to be in a specific locaiton. 

It might be helpful to highlight the locations in the docs.

For example:
 copy `libs` folder into the component’s `<PROJECT_ROOT>/ios` folder
```
<PROJECT_ROOT>/ios/libs/<frameworks>
```

**Comment by Yize9** [comment]
Thanks for your Suggestions. The adjustment has been made

**Comment by naoey** [comment]
@timkomip could you elaborate a bit more on what you mean by specific location? I'm having trouble getting this compiling with my project with the same error as OP.

The documentation is rather vague. When it says "component <platform> folder" does it mean `node_modules/@foxitsoftware/...` or the main project's platform folders? The "component" bit is confusing.

I did try copying the libs folder to both locations, but the build still can't resolve it.

**Comment by timkomip** [comment]
I agree with the "components" bit. 
The libs folder (which contains `FoxitRDK.framework` and `uiextensionsDynamic.framework`) should be in the `ios` folder. The `libs` folder is from the library zip you should have downloaded from FoxIt (with the name: `foxitpdfsdk_6_4_ios.zip`)

You should end up with
`MyFantasticApp/ios/libs/FoxitRDK.framework`
`MyFantasticApp/ios/libs/uiextensionsDynamic.framework`

**Comment by naoey** [comment]
I see. This setup is a bit troublesome for iOS. My project uses CocoaPods for all dependencies (as is recommended in React Native 60 onwards) but Foxit distributes their frameworks outside the pod which makes resolving it during build somewhat of a hassle. Either way if your project is using CocoaPods the setup instructions will not be of help. I'll update this comment if I manage to find a solution, but ideally this library should fully support CocoaPods out of the box.
