### ISSUE TITLE
iOS: Open PDF in any path under documents directory

### ISSUE THREAD

**Issue by naoey** [foxitsoftware/react-native-foxitpdf#8]
Hi,

Is there a reason why the iOS SDK disallows us from opening PDFs from a path not in the root documents directory? Our application stores a lot of files in a spread out directory structure in the documents directory, because of which this is currently a deal-breaker for our project. It seems like somewhat of an arbitrary limitation and would be less of a hassle that these checks not exist and any valid `NSUrl` should be openable?

It seems like this limitation is baked into the closed source SDK, as removing the checks in the React Native module alone doesn't enable this to work (receives an `FSErrFormat` error from the PDF view control).

**Comment by Yize9** [comment]
It is such a child. iOS can only open the directory of the current application. You can create your document in the directory and then open it with my plugin. React-native-fs doesn't know if it can meet your needs.

**Comment by naoey** [comment]
I did mean in the sub directory of the current application. Ex: a file at Documents/some/other/folder/file.pdf is not openable. It only accepts Documents/file.pdf, which is a limitation of this library and not react-native-fs or iOS.
